[package]
name = "wifi_backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "wifi_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
anyhow = "1"
neli-wifi = "0.5"
serde = "1"
serde_json = "1"
neli = "0.4.4"